#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json

import agent

agent.set_weight(os.path.basename(__file__), 0)  # validation step, no progress weight

data = json.load(sys.stdin)
host = data.get("host")
old_host = os.environ.get("TRAEFIK_HOST", "")

# Refuse a host name already routed by Traefik to another instance.
if host != old_host and agent.http_route_in_use(domain=host):
    agent.set_status("validation-failed")
    json.dump(
        [{"field": "host", "parameter": "host", "value": host, "error": "domain_already_used_in_traefik"}],
        fp=sys.stdout,
    )
    sys.exit(2)
