#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Remove the Traefik route created by configure-module.

import os
import sys
import json

import agent
import agent.tasks

# stdin is consumed even if unused, to follow the action protocol.
json.load(sys.stdin)

default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='delete-route',
    data={'instance': os.environ['MODULE_ID']},
)
agent.assert_exp(response['exit_code'] == 0)
